### ISSUE TITLE
게시물 보기 페이지

### ISSUE THREAD

**Issue by jeonoseung** [algorithmQNA/algorithmQNA_backend#49]
1. 게시물 보기에서 postType, postCategory, 조회수가 필요합니다.
2. 게시물 수정 요청 시 권한이 없을 때 게시물을 삭제할 권한이 없습니다라고 출력됩니다.
    테스트할 때 밖에 볼일 없지만 혹시나해서 코멘트 남깁니다.(2023-06-15)

**Comment by janguni** [comment]
넵 수정해놓겠습니다!
