### ISSUE TITLE
게시물 하이라이팅 응답이 오지 않음

### ISSUE THREAD

**Issue by bebusl** [algorithmQNA/algorithmQNA_backend#50]
# 문제상황
게시글 조회시 붙어오는 pinnedComment로 highlighting api를 호출하였으나 404 에러가 옵니다.

* 본 게시글의 postId는 102, pinnedComment의 commentId는 149
![image](https://github.com/algorithmQNA/algorithmQNA_backend/assets/49019236/3287dd48-751a-4a61-8d79-de3e8ebf49ee)

* /api/post/102/highlight/149 요청시 404에러 
![image](https://github.com/algorithmQNA/algorithmQNA_backend/assets/49019236/bd5b0b08-94d2-4390-bb7e-39f0a6ad26d8)

# 정상응답
* /api/post/102/highlight/149 요청시 게시글 + 댓글이 펼쳐진상태로 응답이 와야함
* 잘못된 응답이더라도 404 status code와 함께 error response body에 "게시물이 존재하지 않습니다." 혹은 "댓글이 존재하지 않습니다."등의 msg필드가 함께 와야함

**Comment by janguni** [comment]
path 보니까 hightlight 라고 요청보내서 오류난 난 것 같아요!
hightlight -> highlight 로 고치시면 될 거예요!

**Comment by bebusl** [comment]
앗 그렇네요....!!!!! 죄송합니다 눈이 어떻게 됐었나봐요

**Comment by bebusl** [comment]
![image](https://github.com/algorithmQNA/algorithmQNA_backend/assets/49019236/856263ce-f3bb-42e1-899b-9aba553ddd29)

응답은 제대로 오는데 commentList가 비어서 옵니다
![image](https://github.com/algorithmQNA/algorithmQNA_backend/assets/49019236/445f78e5-888c-4639-b085-686b1306127e)

**Comment by janguni** [comment]
확인해보니까 하이라이팅 댓글의 최상위 댓글 페이지를 잘못 계산하고 있었습니다. 수정해서 재배포 완료했습니다!
