### ISSUE TITLE
신고 내역 삭제 안됨

### ISSUE THREAD

**Issue by bebusl** [algorithmQNA/algorithmQNA_backend#64]
## 문제 상황
1. 댓글 신고
* 신고 내역 삭제 안됨 (위 사진과 같이 404에러 뜸)
* 신고받은 글 삭제 안됨 ( 게시글가서 댓글확인해보면 댓글 존재하는데 '존재하지 않는 댓글입니다' 라고 응답옴)
![image](https://github.com/algorithmQNA/algorithmQNA_backend/assets/49019236/cc975ed2-c7a8-42f7-97b8-cebf1cbc4011)
![image](https://github.com/algorithmQNA/algorithmQNA_backend/assets/49019236/515837a3-6be9-4ad8-a9af-28d38db4cd3e)

2. 게시글 신고도 마찬가지로 모두 404에러 뜹니다.
![image](https://github.com/algorithmQNA/algorithmQNA_backend/assets/49019236/e1145a1d-b0fe-4dca-8fb9-6e973795281d)
![image](https://github.com/algorithmQNA/algorithmQNA_backend/assets/49019236/1ca121dd-8c55-415a-a99b-5d794279777e)

## 주의사항
* 관리자 권한이 있는 계정으로 로그인해야 관리자 페이지 헤더에 메뉴가 보입니다.
![image](https://github.com/algorithmQNA/algorithmQNA_backend/assets/49019236/00b52092-d94c-449f-ac27-c0f4af51d0af)

**Comment by so1omon** [comment]
Resolved : https://github.com/algorithmQNA/algorithmQNA_backend/pull/65
