### ISSUE TITLE
알람 데이터 조회

### ISSUE THREAD

**Issue by jeonoseung** [algorithmQNA/algorithmQNA_backend#69]
데이터를 조회할 때 다음 목록 또는 최신 알람 목록을 불러올 때 파라미터 recentAlarmId or oldAlarmId로 값을 주면
/alarm으로 조회한 데이터와 똑같은 데이터를 불러옵니다.
![image](https://github.com/algorithmQNA/algorithmQNA_backend/assets/114666481/e666c20c-0ec3-4228-8546-f8bdd1609f39)
한번 확인 부탁드립니다.

**Comment by so1omon** [comment]
> 데이터를 조회할 때 다음 목록 또는 최신 알람 목록을 불러올 때 파라미터 recentAlarmId or oldAlarmId로 값을 주면
> /alarm으로 조회한 데이터와 똑같은 데이터를 불러옵니다.
> ![image](https://github.com/algorithmQNA/algorithmQNA_backend/assets/114666481/e666c20c-0ec3-4228-8546-f8bdd1609f39)
> 한번 확인 부탁드립니다.
> 

어우 개판이네요.. 내일까지 해결할게요!

**Comment by jeonoseung** [comment]
전과 같이 조회 시 이번에는 500에러가 발생합니다 
확인 부탁드립니다

**Comment by so1omon** [comment]
query문의 table정보가 비정상적으로 입력되고 있었습니다. 수정 완료했습니다.
